[package]
name = "BitcoinMiner"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = "0.4.1"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.38.0", features = ["full"] }
